import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import Headbar from './components/headbar'
import ContentBox from './components/contentBox'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Miikatur',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <div className='bg-gradient-to-b from-yellow-300 from-10% via-white via-20% to-sky-400 to-100% '>
      <div id="navigation" className='md:px-12'>
        <Navbar />
      </div>
      <div id="body" className='md:px-36'>
        <Headbar />
        <ContentBox />
      </div>
    </div>
  )
}
