import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Miikatur',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='bg-slate-100 h-full'>

    <Navbar/>
    </div>
  )
}
